USE master;
GO

CREATE DATABASE QUANLYSINHVIEN ON 
(FILENAME = 'D:\Program Files\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QUANLYSINHVIEN.mdf'), 
(FILENAME = 'D:\Program Files\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\QUANLYSINHVIEN_log.ldf')
FOR ATTACH;
GO
